[package]
name = "add-reminders"
version = "0.1.1"
edition = "2024"

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
regex = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
chrono = { workspace = true }
